<!-- GitHub Star -->
<iframe src="https://ghbtns.com/github-btn.html?user=baomidou&repo=mybatis-plus&type=star" frameborder="0" scrolling="0" width="84px" height="20px"></iframe>
<!-- GitHub fork -->
<iframe src="https://ghbtns.com/github-btn.html?user=baomidou&repo=mybatis-plus&type=fork" frameborder="0" scrolling="0" width="84px" height="20px"></iframe>
<!-- GitHub Release -->
<a href="https://github.com/baomidou/mybatis-plus/releases"><img src="https://img.shields.io/github/release/baomidou/mybatis-plus.svg?maxAge=2592000"></a>